### ISSUE TITLE
One Plus 9 fingerprint unlock calls onSucceeded when dialog is cancelled

### ISSUE THREAD

**Issue by jamiehiggins** [sergeykomlach/AdvancedBiometricPromptCompat#305] opened 2022-08-12 19:37 UTC
When testing the library on the One Plus 9 I have noticed that if I cancel the dialog while prompting for a fingerprint, instead of getting an onCanceled callback like I do on other devices I am seeing an onSucceeded callback. This is allowing users to bypass the security lock simply by cancelling the dialog.

There appears to be no difference in the onSucceeded callback on this device if I do actually authenticate with my fingerprint as the return parameter is identical.

**Comment by jamiehiggins** [comment] 2022-08-12 19:47
Apologies, it was my own mistake. Closing this.

**Comment by sergeykomlach** [comment] 2022-08-15 06:36
Sounds like a critical issue.
I have a OnePlus 8T device, but with the test app, all works fine, including the case with dialog cancel.

Can you provide more details about this case?
- Did you try the test APK https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/main/app/app-debug.apk ?
For all authorization methods, are you able to reproduce `onSucceeded` call after dialog dismiss OR only some of them?
- What  `BiometricAuthRequest` did you use to start the Biometric auth flow?
- And most important - when `onSucceeded` is called, it receives the `Set<AuthenticationResult>`  (the test app shows info in Toast) - can you provide what AuthenticationResult(s) you got if you dismiss the dialog?

**Comment by jamiehiggins** [comment] 2022-08-15 06:57
I am testing against the latest version 2.1.11, although it also happens on older versions (I first noticed on 2.0.79 and upgraded to latest to test)

The test APK exhibits the same problem when I click any of the buttons and then click to cancel I see a Succeeded popup message.

In my app I am using the following:
BiometricAuthRequest(BiometricApi.AUTO, BiometricType.BIOMETRIC_ANY, BiometricConfirmation.ANY)

The toast is shown below:

![image](https://user-images.githubusercontent.com/1000967/184590032-3d91ff8b-14be-4b05-8a0c-9c979304a65d.png)

My device is running Android 12.

**Comment by jamiehiggins** [comment] 2022-08-15 07:22
On my OnePlus 7 with Android 11 the issue does not happen and everything behaves as it should.

**Comment by sergeykomlach** [comment] 2022-08-15 16:37
@jamiehiggins okay, I checked the code and behavior on my OnePlus 8T/Android 12.
For me both API's (Fingerprint and Biometric) behave in a next way:
- if the user presses the "Cancel" button on the dialog - we receive error code 10 "The user canceled the operation."
- if the user press the "Back" button or tap outside dialog - we receive error code 1010 that it seems like a combination of ERROR_VENDOR_BASE(1000) + ERROR_USER_CANCELED(10)
As result - all works fine, like on your OnePlus 7.

Also, I check more logic - `onSucceeded()` can be called if at least ones called `onAuthenticationSucceeded` . From your report - it seems like touching outside leads to `onAuthenticationSucceeded` for both - Fingerprint and BiometricPrompt API.

Recently I faced with a bug on MS Surface Duo, when `onAuthenticationError` with 10 "The user canceled the operation." was called right after `onAuthenticationFailed`. It's just an idea, but I have a mind that if you touch on outside dialog, the `onAuthenticationSucceeded` called due to some system bug, and then `onAuthenticationError` is called, but ignored.

Is possible to get from your OnePlus 9 device to get logs? 
You can obtain logs from LogCat OR after bug reproducing - press "Send logs".

Thank you.

**Comment by sergeykomlach** [comment] 2022-08-16 17:26
So, I prepare the [build](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/oneplus9_issue/app/app-debug.apk?raw=true)
Testing required

**Comment by jamiehiggins** [comment] 2022-08-16 20:46
Thanks so much for the super quick response. I will test first thing tomorrow morning and report back ASAP.

**Comment by jamiehiggins** [comment] 2022-08-16 21:52
The fix has the same result, I'm afraid. Hitting back or touching outside the dialog returns the correct Canceled result, but hitting the cancel button still shows the success popup.

![image](https://user-images.githubusercontent.com/1000967/184991024-af89db42-913f-4959-b9a8-f8838e1854d3.png)

I can't seem to send logs I'm afraid as it loads up gmail and then hangs before crashing.

**Comment by jamiehiggins** [comment] 2022-08-17 05:43
Here is the logcat output after this issue happens.

[logcat.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9356677/logcat.txt)

**Comment by sergeykomlach** [comment] 2022-08-17 17:42
Okay, step-by-step we moving.
I pushed some changes to `oneplus_9` branch, so fresh test build can be found [here](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/issues/305#issuecomment-1216937064)

**Comment by jamiehiggins** [comment] 2022-08-17 21:24
Result is the same. Updated logcat output is attached:

[logcat_op9.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9366152/logcat_op9.txt)

**Comment by sergeykomlach** [comment] 2022-08-20 17:45
@jamiehiggins 

1. prepared the update, not sure that the issue is fixed, but it may produce some additional information in logcat [APK here](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/oneplus9_issue/app/app-debug.apk?raw=true)
2. Can you try to launch this sample https://github.com/Kieun/android-biometricprompt and reproduce the bug?

**Comment by jamiehiggins** [comment] 2022-08-22 07:30
@sergeykomlach I have just emailed logs from the new APK.

The sample app does get an onAuthenticationSucceeded returned when I hit the cancel button, however it then goes on to hit the SignatureException so it doesn't succeed. (All works fine when I authenticate with the fingerprint).

**Comment by sergeykomlach** [comment] 2022-08-22 15:25
@jamiehiggins thank you for the logs and feedback!
It seems like in case of false `onAuthenticationSucceeded`, if used BiometricCryptoObject - Cipher/Signature is not initialized properly and can't be used for crypto functions. 
I can try to use this to detect the false `onAuthenticationSucceeded` calls. [APK ](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/oneplus9_issue/app/app-debug.apk?raw=true)
Hope this will help

**Comment by jamiehiggins** [comment] 2022-08-22 22:19
@sergeykomlach that APK is working great and I am now getting the cancelled popup when I tap the cancel button. Great work!

**Comment by sergeykomlach** [comment] 2022-08-23 06:03
Super! I'll close the issue and prepare new version of the library

**Closed by sergeykomlach** 2022-08-23 06:03 UTC
Labels: bug
