### ISSUE TITLE
Incorrect behavior of face authentication on Honor Play device

### ISSUE THREAD

**Issue by sandboiii** [sergeykomlach/AdvancedBiometricPromptCompat#276] opened 2022-05-12 12:46 UTC
Device: Honor Play
Android version: 9
There are problems with face authentication on Honor Play. The dialog displays text about fingerprint scanner even though biometric type is BIOMETRIC_FACE and authentication not working on this device.   
  
Video:
  
https://user-images.githubusercontent.com/17468894/168077078-d8ac97fe-aa5e-4dd0-a1bb-af788b911660.mp4
  
Logs:
  
[log1.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/8679117/log1.txt)
[log2.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/8679118/log2.txt)

**Comment by sergeykomlach** [comment] 2022-05-16 13:08
The library does not develop directly for Honor, but as I know, cause Honor is a sub-brand of Huawei, I expect that some API's can also be accessible on Honor devices.
I'll try to investigate why FaceId doesn't work on Honor, I hope it's some minor changes.

Due to texts - used 'system' terma that exists in  ```com.android.internal.R$string```. Probably I need to get a dump from some Huawei/Honor device to get more realistic strings ID's, cause now used 'default' for fingerprint/biometric

**Comment by sergeykomlach** [comment] 2022-05-18 09:40
Okay, can you try test APK with Camera permission request?
https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/blob/main/app/app-debug.apk

**Comment by sandboiii** [comment] 2022-05-18 14:23
Nothing changed. First time there was a face dialog which didn't authenticate. And second time it was just HARDWARE_UNAVAILABLE error  
[log.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/8717080/log.txt)

**Comment by sergeykomlach** [comment] 2022-09-04 16:33
@sandboiii sorry for late response.
I start fixing device specific issues, and problem with Honor Play now in work.
Can you try to test [APK](https://drive.google.com/file/d/1o7loKYsPS_D4WSNdH-2TVZNIWnVMlINt/view?usp=sharing) on your device?

**Comment by sandboiii** [comment] 2022-09-05 12:43
Hey, text about fingerprint is fixed, but face biometric still doesn't work. Some logs like [CheckBiometric.onUIOpened()] are missing for unknown reason.

https://user-images.githubusercontent.com/17468894/188451726-e01f683d-8381-4510-9b37-55f960302c66.mp4

[cor-l29.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9489863/cor-l29.txt)
[cor-l29-2.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9489864/cor-l29-2.txt)
[cor-l29-3.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9489865/cor-l29-3.txt)

**Comment by sandboiii** [comment] 2022-09-05 12:53
I also tested face biometric on huawei p50 pro and it also doesn't work both current main branch and apk which you provided.
But at least there are more logs with all events.

https://user-images.githubusercontent.com/17468894/188453381-6cd983d3-0695-4765-9550-946612aba4fb.mp4

[p50-pro-main.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9489924/p50-pro-main.txt)
[p50-pro-gdrive.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9489925/p50-pro-gdrive.txt)

**Comment by sandboiii** [comment] 2022-09-06 07:57
Yeah, sorry about p50 😬. I actually asked another person to test this app and they didn't know what was supposed to happen. So they said that it didn't work, but actually it does.

**Comment by sergeykomlach** [comment] 2022-09-06 19:39
@sandboiii I see :) Okay, let's close the issue about Huawei P50)
If back to Honor Play. I prepare the build [Huawei3DFaceManager.APK](https://drive.google.com/file/d/1qTCglf2TIWLw8gjyCWbEmhwYcqL6eTkA/view?usp=sharing) - plz check it, and some difference in behavior I hope we will notice.
Thank you

**Comment by sergeykomlach** [comment] 2022-09-09 16:16
Not very clear - user cancel dialog or "manager" do this.
I don't see any fails/errors/success-related Toasts :(

**Comment by sergeykomlach** [comment] 2022-09-12 06:34
@sandboiii any new tests/logs from the latest build?

**Comment by sandboiii** [comment] 2022-09-14 13:27
I hope to get it this week, please wait a little bit more

**Comment by sandboiii** [comment] 2022-09-15 12:53
Here are the logs
[cor-l29 Huawei3dFaceManager.txt](https://github.com/sergeykomlach/AdvancedBiometricPromptCompat/files/9575377/cor-l29.Huawei3dFaceManager.txt)

**Comment by sergeykomlach** [comment] 2022-12-29 09:37
v2.1.40 hope solves the issue

**Comment by sandboiii** [comment] 2022-12-29 10:25
Hey, there is still happens a crash when trying to show callback toast  

https://user-images.githubusercontent.com/17468894/209938007-e26dc844-c727-4860-aa19-1403ec98e07d.mp4

```
beginning of crash
E AndroidRuntime: FATAL EXCEPTION: Thread-2
E AndroidRuntime: Process: dev.skomlach.biometric.app, PID: 17503
E AndroidRuntime: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
E AndroidRuntime: at android.widget.Toast$TN.<init>(Toast.java:393)
E AndroidRuntime: at android.widget.Toast.<init>(Toast.java:117)
E AndroidRuntime: at android.widget.Toast.makeText(Toast.java:280)
E AndroidRuntime: at android.widget.Toast.makeText(Toast.java:270)
E AndroidRuntime: at dev.skomlach.biometric.app.utils.BiometricExtensionKt$startBiometric$1.onUIClosed(BiometricExtension.kt:176)
E AndroidRuntime: at dev.skomlach.biometric.compat.BiometricPromptCompat$startAuth$1$callback$1.onUIClosed(BiometricPromptCompat.kt:568)
E AndroidRuntime: at dev.skomlach.biometric.compat.BiometricPromptCompat$startAuth$1$callback$1.onCanceled(BiometricPromptCompat.kt:502)
E AndroidRuntime: at dev.skomlach.biometric.compat.impl.BiometricPromptGenericImpl.cancelAuth(BiometricPromptGenericImpl.kt:103)
E AndroidRuntime: at dev.skomlach.biometric.compat.impl.BiometricPromptGenericImpl$BiometricAuthenticationCallbackImpl.onCanceled(BiometricPromptGenericImpl.kt:211)
E AndroidRuntime: at dev.skomlach.biometric.compat.engine.BiometricAuthentication$authenticate$1.onCanceled(BiometricAuthentication.kt:322)
E AndroidRuntime: at dev.skomlach.biometric.compat.engine.internal.face.huawei.HuaweiFaceUnlockModule$AuthCallbackLegacy.onAuthenticationError(HuaweiFaceUnlockModule.kt:160)
E AndroidRuntime: at dev.skomlach.biometric.compat.engine.internal.face.huawei.impl.HuaweiFaceRecognizeManager$mFRCallback$1.onCallbackEvent(HuaweiFaceRecognizeManager.kt:186)
E AndroidRuntime: at com.huawei.facerecognition.FaceRecognizeManager$1.onCallbackEvent(FaceRecognizeManager.java:150)
E AndroidRuntime: at huawei.android.security.facerecognition.FaceRecognizeManagerImpl$CallbackHolder.onCallbackEvent(FaceRecognizeManagerImpl.java:674)
E AndroidRuntime: at huawei.android.security.facerecognition.task.AuthenticateTask$1.onTaskCallback(AuthenticateTask.java:68)
E AndroidRuntime: at huawei.android.security.facerecognition.base.HwSecurityTaskBase.endWithResult(HwSecurityTaskBase.java:82)
E AndroidRuntime: at huawei.android.security.facerecognition.task.PrepareCameraTask.access$500(PrepareCameraTask.java:12)
E AndroidRuntime: at huawei.android.security.facerecognition.task.PrepareCameraTask$2.onTaskCallback(PrepareCameraTask.java:48)
E AndroidRuntime: at huawei.android.security.facerecognition.base.HwSecurityTaskBase.endWithResult(HwSecurityTaskBase.java:82)
E AndroidRuntime: at huawei.android.security.facerecognition.task.OpenCameraRetryTask.access$500(OpenCameraRetryTask.java:14)
E AndroidRuntime: at huawei.android.security.facerecognition.task.OpenCameraRetryTask$2.onTaskCallback(OpenCameraRetryTask.java:47)
E AndroidRuntime: at huawei.android.security.facerecognition.base.HwSecurityTaskBase.endWithResult(HwSecurityTaskBase.java:82)
E AndroidRuntime: at huawei.android.security.facerecognition.base.HwSecurityTaskBase.execute(HwSecurityTaskBase.java:56)
E AndroidRuntime: at huawei.android.security.facerecognition.base.HwSecurityTaskThread.run(HwSecurityTaskThread.java:85)
```

**Comment by sandboiii** [comment] 2022-12-29 10:38
Looks like this toast tried to show error message `onAuthenticationError`

**Comment by sergeykomlach** [comment] 2023-01-17 18:01
So the issue is that on some Huawei/Honor devices API is accessible, but API cannot start the Camera due to permissions restrictions. 
Adding and granting permissions directly to the library doesn't solves the problem.
The only solution I can suggest - detect in some way devices with blocked Camera and "hide" face API.

**Comment by sergeykomlach** [comment] 2023-02-02 20:17
So, after months of investigations together with @sandboiii - this ticket will be closed as "partially fixed".
Some Huawei/Honor devices have failed on camera launch when face authentification started (errorCode=12 aka CAMERA_FAILED), at the same time `isHardwareAvailable` is TRUE and no chance to identify such behavior earlier than authentification started.

As a fix for this problem was developed the solution that checks once for CAMERA_FAILED errorCode and memorizes results for future calls, so if the device has broken camera access, the FaceAuth feature will be not available on device.

In other cases, FaceAuth should work properly for Huawei/Honor

**Closed by sergeykomlach** 2023-02-02 20:17 UTC
